"""Install the reviewed Objaverse building set into the locked asset manifest.

The installer is deliberately fail-closed.  It accepts only the eight reviewed
Objaverse UIDs below, requires an explicit CC BY attribution record for every
source GLB, converts each source with Kit's Asset Converter, and validates the
resulting USD with OpenUSD before updating the production manifest.

No geometry is generated by this module.  The only authored geometry-bearing
layers are the Asset Converter outputs; the USDA files written here are
metre/Z-up grounding wrappers around those converted sources.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import math
import os
import re
import shutil
import struct
import sys
import time
import uuid
from pathlib import Path, PurePosixPath
from typing import Any, Callable, Iterable, Mapping
from urllib.parse import urlparse

from fireviewer_sdg.simready_assets import (
    MANIFEST_PROFILE,
    MANIFEST_SCHEMA_VERSION,
    PHOTOREAL_FAMILY_MINIMUMS,
    PHOTOREAL_LIBRARY_POLICY,
)


INSTALL_STATE = "COMMUNITY_BUILDING_ASSETS_INSTALLED"
INSTALL_SCHEMA_VERSION = 1
PROVIDER = "Objaverse"
CONVERTER_ID = "omni.kit.asset_converter"
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_TEXTURE_SUFFIXES = frozenset(
    {".bmp", ".exr", ".jpeg", ".jpg", ".png", ".tga", ".tif", ".tiff", ".tx"}
)
_USD_SUFFIXES = frozenset({".usd", ".usda", ".usdc", ".usdz"})
_DIMENSION_LIMITS_M: dict[str, tuple[float, float, float, float]] = {
    "agricultural": (2.0, 450.0, 2.0, 100.0),
    "industrial": (2.0, 700.0, 2.0, 150.0),
    "annex": (0.5, 200.0, 1.0, 60.0),
}
_UNIT_SCALE_CORRECTIONS: dict[str, float] = {
    # Reviewed source geometry and visual evidence: these assets are authored
    # in inches although their converted layers declare centimetre world units.
    "aab826498d5b42fabb46e8c53f69a66c": 0.0254,
    "70154ba65c7d4ba0b5f081fd0eb35f68": 0.0254,
}

# This mapping is a reviewed input contract, not an inferred relabelling step.
COMMUNITY_BUILDING_UIDS: dict[str, tuple[str, ...]] = {
    "agricultural": (
        "bcdac4f85bb940aaa189f22f869ed11f",
        "aab826498d5b42fabb46e8c53f69a66c",
        "3447582ca28743d785d08f04ea710469",
    ),
    "industrial": (
        "0e93ab7b05944087b4a19fb7262877fa",
        "3ebb228ec3ad441c850e0fd298223348",
    ),
    "annex": (
        "d790f2d3d93d4ad09c8c40f5331e5813",
        "70154ba65c7d4ba0b5f081fd0eb35f68",
        "cf8074f44da541189bb4936b05f4f434",
    ),
}
COMMUNITY_BUILDING_TITLES: dict[str, str] = {
    "bcdac4f85bb940aaa189f22f869ed11f": "Cow Shed",
    "aab826498d5b42fabb46e8c53f69a66c": "Abandoned Barn",
    "3447582ca28743d785d08f04ea710469": "Farm Out Building complex",
    "0e93ab7b05944087b4a19fb7262877fa": "Industrial Building drone",
    "3ebb228ec3ad441c850e0fd298223348": "sand-lime brick factory",
    "d790f2d3d93d4ad09c8c40f5331e5813": "Fergus Falls cottage",
    "70154ba65c7d4ba0b5f081fd0eb35f68": "Backyard Utility Shed",
    "cf8074f44da541189bb4936b05f4f434": (
        "Wooden shed/open rural structure"
    ),
}
UID_TO_FAMILY = {
    uid: family
    for family, uids in COMMUNITY_BUILDING_UIDS.items()
    for uid in uids
}
# These exact provider objects were validated on the production pod.  Keeping
# the byte locks next to the reviewed UID/family contract lets the downloader,
# installer-resume verifier and source-manifest merge share one authority.
COMMUNITY_BUILDING_GLB_LOCKS: dict[str, dict[str, object]] = {
    "0e93ab7b05944087b4a19fb7262877fa": {
        "sha256": "390d20795f124f5157fb60dccc4803833a59f40d256b1386c6f481454fb0144f",
        "size_bytes": 171_729_640,
    },
    "3447582ca28743d785d08f04ea710469": {
        "sha256": "4c06f380f157097752b1c77e8465b0ed724299a939674f65f5170dd5137d4530",
        "size_bytes": 4_522_804,
    },
    "3ebb228ec3ad441c850e0fd298223348": {
        "sha256": "f5442862aa0560695899df72929f9da09b87bfc5f8087e3800a4726981842743",
        "size_bytes": 290_421_108,
    },
    "70154ba65c7d4ba0b5f081fd0eb35f68": {
        "sha256": "4ffb197402ddc2660ae22357d7a5cfd130f30520ba87e441a103daa942657e53",
        "size_bytes": 15_852_908,
    },
    "aab826498d5b42fabb46e8c53f69a66c": {
        "sha256": "c7fbfec4d5b1cf477c607b5b7c5c4281cd6eb075ac443d6533818c90fe03b7c9",
        "size_bytes": 122_842_960,
    },
    "bcdac4f85bb940aaa189f22f869ed11f": {
        "sha256": "0d0e475bd0295a025d95d2f11bab94075d8d5413dab60f6e01b373e4edeca8b1",
        "size_bytes": 29_062_804,
    },
    "cf8074f44da541189bb4936b05f4f434": {
        "sha256": "fbc7ea33b61b960ba68c8531000f5f4775922af85f1db3d069e145a59004e92a",
        "size_bytes": 5_339_172,
    },
    "d790f2d3d93d4ad09c8c40f5331e5813": {
        "sha256": "7ffc941ae3cbe8f335dd8e5872bc3e70ff39b6dc5b80a01eeb04786aaa8d60b1",
        "size_bytes": 128_291_692,
    },
}


class CommunityBuildingAssetError(RuntimeError):
    """Raised when the community asset supplement cannot be trusted."""


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while block := stream.read(4 * 1024 * 1024):
            digest.update(block)
    return digest.hexdigest()


def _canonical_sha256(value: object) -> str:
    return hashlib.sha256(
        json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    ).hexdigest()


def _inside(root: Path, path: Path) -> bool:
    resolved_root = root.resolve()
    resolved_path = path.resolve()
    return resolved_path == resolved_root or resolved_root in resolved_path.parents


def _atomic_write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    temporary.write_text(
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    os.replace(temporary, path)


def _atomic_write_text(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    temporary.write_text(value, encoding="utf-8", newline="\n")
    os.replace(temporary, path)


def _read_json(path: Path, *, label: str) -> dict[str, Any]:
    if not path.is_file() or path.is_symlink():
        raise CommunityBuildingAssetError(f"{label} is absent: {path}")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise CommunityBuildingAssetError(
            f"{label} is not valid JSON: {path}"
        ) from exc
    if not isinstance(payload, dict):
        raise CommunityBuildingAssetError(f"{label} must be a JSON object")
    return payload


def _validate_https(value: object, *, label: str) -> str:
    text = str(value or "").strip()
    parsed = urlparse(text)
    if parsed.scheme != "https" or not parsed.hostname:
        raise CommunityBuildingAssetError(f"{label} must be an HTTPS URL")
    return text


def _extract_records(payload: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    raw_assets: object = payload.get("assets", payload)
    records: dict[str, dict[str, Any]] = {}
    if isinstance(raw_assets, Mapping):
        iterator: Iterable[tuple[object, object]] = raw_assets.items()
        for key, raw in iterator:
            if not isinstance(raw, Mapping):
                continue
            record = dict(raw)
            uid = str(record.get("uid") or record.get("id") or key).strip()
            if uid:
                records[uid] = record
    elif isinstance(raw_assets, list):
        for raw in raw_assets:
            if not isinstance(raw, Mapping):
                continue
            record = dict(raw)
            uid = str(record.get("uid") or record.get("id") or "").strip()
            if uid:
                if uid in records:
                    raise CommunityBuildingAssetError(
                        f"metadata repeats Objaverse UID {uid}"
                    )
                records[uid] = record
    else:
        raise CommunityBuildingAssetError(
            "metadata.assets must be an object or list"
        )
    missing = sorted(set(UID_TO_FAMILY) - set(records))
    if missing:
        raise CommunityBuildingAssetError(
            "metadata is missing reviewed Objaverse UIDs: " + ", ".join(missing)
        )
    return {uid: records[uid] for uid in UID_TO_FAMILY}


def _metadata_value(
    record: Mapping[str, Any],
    *keys: str,
) -> object:
    for key in keys:
        if key in record and record[key] not in (None, ""):
            return record[key]
    return None


def _normalized_metadata(
    *,
    uid: str,
    family: str,
    record: Mapping[str, Any],
) -> dict[str, Any]:
    declared_family = str(
        _metadata_value(record, "fireviewer_family", "family") or family
    ).strip()
    if declared_family not in {family, f"buildings.{family}"}:
        raise CommunityBuildingAssetError(
            f"{uid} metadata family {declared_family!r} disagrees with the "
            f"reviewed {family!r} mapping"
        )

    licence = record.get("license")
    licence_record = dict(licence) if isinstance(licence, Mapping) else {}
    licence_id = str(
        _metadata_value(record, "license_id", "license_name")
        or licence_record.get("id")
        or (licence if isinstance(licence, str) else "")
    ).strip()
    licence_uri = _validate_https(
        _metadata_value(record, "license_uri", "license_url")
        or licence_record.get("uri")
        or licence_record.get("url"),
        label=f"{uid} license URL",
    )
    normalized_licence = re.sub(r"[^a-z0-9]+", "", licence_id.casefold())
    licence_url = urlparse(licence_uri)
    path_parts = [part.casefold() for part in licence_url.path.split("/") if part]
    is_cc_by_url = (
        licence_url.hostname.casefold().endswith("creativecommons.org")
        and len(path_parts) >= 2
        and path_parts[0] == "licenses"
        and path_parts[1] == "by"
    )
    if normalized_licence not in {
        "by",
        "ccby",
        "ccby30",
        "ccby40",
        "creativecommonsattribution",
        "creativecommonsattribution30",
        "creativecommonsattribution40",
    } or not is_cc_by_url:
        raise CommunityBuildingAssetError(
            f"{uid} must carry an explicit CC BY license, not {licence_id!r}"
        )

    source_uri = _validate_https(
        _metadata_value(record, "source_uri", "uri", "source_url", "url"),
        label=f"{uid} source URI",
    )
    title = str(_metadata_value(record, "title", "name") or "").strip()
    if not title:
        raise CommunityBuildingAssetError(f"{uid} metadata has no asset title")
    attribution = record.get("attribution")
    attribution_record = (
        dict(attribution) if isinstance(attribution, Mapping) else {}
    )
    creator = str(
        _metadata_value(record, "creator", "author", "artist")
        or attribution_record.get("creator")
        or attribution_record.get("author")
        or ""
    ).strip()
    notice = str(
        _metadata_value(record, "attribution_text", "credit")
        or attribution_record.get("notice")
        or (attribution if isinstance(attribution, str) else "")
    ).strip()
    if not creator and not notice:
        raise CommunityBuildingAssetError(
            f"{uid} metadata has no creator or attribution notice"
        )
    if not notice:
        notice = f"{title} — {creator}"

    raw_local = _metadata_value(record, "local_path", "path")
    local_path = str(raw_local).strip() if raw_local is not None else f"{uid}.glb"
    relative = PurePosixPath(local_path.replace("\\", "/"))
    if (
        relative.is_absolute()
        or not relative.parts
        or ".." in relative.parts
        or relative.suffix.casefold() != ".glb"
    ):
        raise CommunityBuildingAssetError(
            f"{uid} local_path must be a safe relative GLB path"
        )
    return {
        "uid": uid,
        "family": family,
        "title": title,
        "creator": creator,
        "attribution_notice": notice,
        "source_uri": source_uri,
        "license_id": licence_id,
        "license_uri": licence_uri,
        "local_path": relative.as_posix(),
        "raw_metadata_sha256": _canonical_sha256(record),
    }


def _validate_glb(path: Path, *, uid: str) -> dict[str, int]:
    if not path.is_file() or path.is_symlink():
        raise CommunityBuildingAssetError(f"{uid} GLB is absent: {path}")
    with path.open("rb") as stream:
        header = stream.read(12)
        if len(header) != 12:
            raise CommunityBuildingAssetError(f"{uid} GLB header is truncated")
        magic, version, total_length = struct.unpack("<4sII", header)
        if magic != b"glTF" or version != 2 or total_length != path.stat().st_size:
            raise CommunityBuildingAssetError(
                f"{uid} is not a complete binary glTF 2.0 asset"
            )
        document: dict[str, Any] | None = None
        while stream.tell() < total_length:
            raw_chunk = stream.read(8)
            if len(raw_chunk) != 8:
                raise CommunityBuildingAssetError(
                    f"{uid} GLB chunk header is truncated"
                )
            chunk_length, chunk_type = struct.unpack("<II", raw_chunk)
            chunk = stream.read(chunk_length)
            if len(chunk) != chunk_length:
                raise CommunityBuildingAssetError(
                    f"{uid} GLB chunk payload is truncated"
                )
            if chunk_type == 0x4E4F534A:
                try:
                    value = json.loads(chunk.rstrip(b" \t\r\n\x00").decode("utf-8"))
                except (UnicodeDecodeError, json.JSONDecodeError) as exc:
                    raise CommunityBuildingAssetError(
                        f"{uid} GLB JSON chunk is invalid"
                    ) from exc
                if isinstance(value, dict):
                    document = value
    if document is None:
        raise CommunityBuildingAssetError(f"{uid} GLB has no JSON scene chunk")
    meshes = document.get("meshes")
    materials = document.get("materials")
    textures = document.get("textures")
    images = document.get("images")
    if not isinstance(meshes, list) or not meshes:
        raise CommunityBuildingAssetError(f"{uid} GLB has no source mesh")
    primitive_count = 0
    for mesh in meshes:
        primitives = mesh.get("primitives") if isinstance(mesh, Mapping) else None
        if not isinstance(primitives, list):
            continue
        for primitive in primitives:
            attributes = (
                primitive.get("attributes")
                if isinstance(primitive, Mapping)
                else None
            )
            if isinstance(attributes, Mapping) and "POSITION" in attributes:
                primitive_count += 1
    if primitive_count < 1:
        raise CommunityBuildingAssetError(
            f"{uid} GLB has no POSITION-bearing mesh primitive"
        )
    if not isinstance(materials, list) or not materials:
        raise CommunityBuildingAssetError(f"{uid} GLB has no source material")
    if (
        not isinstance(textures, list)
        or not textures
        or not isinstance(images, list)
        or not images
    ):
        raise CommunityBuildingAssetError(f"{uid} GLB has no source texture")
    return {
        "mesh_count": len(meshes),
        "primitive_count": primitive_count,
        "material_count": len(materials),
        "texture_count": len(textures),
        "image_count": len(images),
    }


def _set_context_option(context: object, name: str, value: object) -> None:
    if hasattr(context, name):
        setattr(context, name, value)


def _kit_asset_convert(source: Path, destination: Path) -> None:
    """Convert a GLB with the active Kit runtime and no geometry shortcuts."""

    try:
        import omni.kit.app
        import omni.kit.asset_converter as asset_converter
    except ImportError as exc:  # pragma: no cover - requires Kit
        raise CommunityBuildingAssetError(
            "GLB conversion requires an active Kit/Isaac runtime with "
            "omni.kit.asset_converter"
        ) from exc
    app = omni.kit.app.get_app()
    manager = app.get_extension_manager()
    if not manager.is_extension_enabled("omni.kit.asset_converter"):
        manager.set_extension_enabled_immediate("omni.kit.asset_converter", True)
    converter = asset_converter.get_instance()
    if converter is None:
        raise CommunityBuildingAssetError(
            "omni.kit.asset_converter returned no converter instance"
        )
    context = asset_converter.AssetConverterContext()
    for name, value in {
        "ignore_materials": False,
        "ignore_animation": True,
        "ignore_animations": True,
        "ignore_cameras": True,
        "ignore_lights": True,
        "merge_all_meshes": False,
        "single_mesh": False,
        "smooth_normals": True,
        "export_preview_surface": True,
        "embed_textures": False,
        "use_meter_as_world_unit": False,
        "baking_scales": True,
    }.items():
        _set_context_option(context, name, value)
    destination.parent.mkdir(parents=True, exist_ok=True)
    task = converter.create_converter_task(
        str(source),
        str(destination),
        lambda _current, _total: True,
        context,
    )
    awaitable = task.wait_until_finished()
    loop = asyncio.new_event_loop()
    try:
        future = loop.create_task(awaitable)
        deadline = time.monotonic() + 1800.0
        while not future.done():
            if time.monotonic() >= deadline:
                future.cancel()
                raise CommunityBuildingAssetError(
                    f"Asset Converter timed out for {source.name}"
                )
            loop.run_until_complete(asyncio.sleep(0))
            app.update()
        succeeded = bool(future.result())
    finally:
        loop.close()
    if not succeeded:
        detail = ""
        getter = getattr(task, "get_error_message", None)
        if callable(getter):
            detail = str(getter() or "").strip()
        raise CommunityBuildingAssetError(
            f"Asset Converter failed for {source.name}"
            + (f": {detail}" if detail else "")
        )
    if not destination.is_file() or destination.stat().st_size == 0:
        raise CommunityBuildingAssetError(
            f"Asset Converter produced no USD for {source.name}"
        )


def _dependency_path(raw: object) -> Path:
    value = str(raw).strip()
    if value.startswith("@") and value.endswith("@"):
        value = value[1:-1]
    return Path(value).resolve()


def _inspect_converted_usd(
    path: Path,
    asset_root: Path,
    family: str,
) -> dict[str, Any]:
    """Inspect the converted layer with OpenUSD inside Kit/Isaac."""

    try:
        from pxr import Usd, UsdGeom, UsdShade, UsdUtils
    except ImportError as exc:  # pragma: no cover - requires Kit/Isaac
        raise CommunityBuildingAssetError(
            "USD validation requires the pinned Kit/Isaac OpenUSD runtime"
        ) from exc
    stage = Usd.Stage.Open(str(path), load=Usd.Stage.LoadAll)
    if stage is None:
        raise CommunityBuildingAssetError(f"converted USD cannot be opened: {path}")
    default_prim = stage.GetDefaultPrim()
    if not default_prim or not default_prim.IsValid():
        raise CommunityBuildingAssetError(
            f"converted USD has no valid default prim: {path}"
        )
    meters_per_unit = float(UsdGeom.GetStageMetersPerUnit(stage))
    up_axis = str(UsdGeom.GetStageUpAxis(stage))
    if (
        not math.isfinite(meters_per_unit)
        or not 0.000001 <= meters_per_unit <= 1000.0
        or up_axis not in {"Y", "Z"}
    ):
        raise CommunityBuildingAssetError(
            f"converted USD has invalid units/up axis: {meters_per_unit}, {up_axis}"
        )
    bbox = UsdGeom.BBoxCache(
        Usd.TimeCode.Default(),
        [UsdGeom.Tokens.default_, UsdGeom.Tokens.render],
        useExtentsHint=False,
    ).ComputeWorldBound(default_prim).ComputeAlignedRange()
    if bbox.IsEmpty():
        raise CommunityBuildingAssetError(f"converted USD has empty bounds: {path}")
    minimum = [float(bbox.GetMin()[index]) for index in range(3)]
    maximum = [float(bbox.GetMax()[index]) for index in range(3)]
    if any(
        not math.isfinite(value) or abs(value) >= 1.0e30
        for value in (*minimum, *maximum)
    ):
        raise CommunityBuildingAssetError(
            f"converted USD has non-finite bounds: {path}"
        )
    source_dimensions = [
        (maximum[index] - minimum[index]) * meters_per_unit for index in range(3)
    ]
    if up_axis == "Z":
        dimensions = source_dimensions
        anchor = [
            (minimum[0] + maximum[0]) * 0.5 * meters_per_unit,
            (minimum[1] + maximum[1]) * 0.5 * meters_per_unit,
            minimum[2] * meters_per_unit,
        ]
    else:
        dimensions = [
            source_dimensions[0],
            source_dimensions[2],
            source_dimensions[1],
        ]
        anchor = [
            (minimum[0] + maximum[0]) * 0.5 * meters_per_unit,
            -(minimum[2] + maximum[2]) * 0.5 * meters_per_unit,
            minimum[1] * meters_per_unit,
        ]

    mesh_count = 0
    point_count = 0
    material_count = 0
    bound_material_count = 0
    for prim in stage.Traverse():
        if prim.IsA(UsdShade.Material):
            material_count += 1
        if prim.IsA(UsdGeom.Mesh):
            mesh_count += 1
            points = UsdGeom.Mesh(prim).GetPointsAttr().Get()
            point_count += len(points) if points is not None else 0
        if prim.IsA(UsdGeom.Gprim):
            material, _relationship = (
                UsdShade.MaterialBindingAPI(prim).ComputeBoundMaterial()
            )
            if material and material.GetPrim().IsValid():
                bound_material_count += 1
    if mesh_count < 1 or point_count < 4:
        raise CommunityBuildingAssetError(
            f"converted USD has no usable mesh geometry: {path}"
        )
    if material_count < 1 or bound_material_count < mesh_count:
        raise CommunityBuildingAssetError(
            "converted USD does not preserve a bound material for every mesh: "
            f"{path}"
        )

    _layers, resolved_assets, unresolved_assets = UsdUtils.ComputeAllDependencies(
        str(path)
    )
    unresolved = sorted({str(item) for item in unresolved_assets if str(item).strip()})
    if unresolved:
        raise CommunityBuildingAssetError(
            "converted USD has unresolved standalone dependencies: "
            + ", ".join(unresolved[:20])
        )
    dependency_paths = {path.resolve()}
    root = asset_root.resolve()
    for raw in resolved_assets:
        dependency = _dependency_path(raw)
        if (
            not dependency.is_file()
            or dependency.is_symlink()
            or not _inside(root, dependency)
        ):
            raise CommunityBuildingAssetError(
                f"converted USD dependency escaped its standalone asset root: {raw}"
            )
        dependency_paths.add(dependency)
    texture_paths = sorted(
        dependency
        for dependency in dependency_paths
        if dependency.suffix.casefold() in _TEXTURE_SUFFIXES
    )
    if not texture_paths:
        raise CommunityBuildingAssetError(
            f"converted USD has no materialized texture dependency: {path}"
        )
    return {
        "source_meters_per_unit": meters_per_unit,
        "source_up_axis": up_axis,
        "default_prim": str(default_prim.GetPath()),
        "dimensions_m": dimensions,
        "anchor_m": anchor,
        "mesh_prim_count": mesh_count,
        "geometry_point_count": point_count,
        "material_prim_count": material_count,
        "bound_material_prim_count": bound_material_count,
        "dependency_paths": sorted(dependency_paths),
        "texture_paths": texture_paths,
        "unresolved_dependencies": [],
    }


def _validate_inspection(
    inspection: Mapping[str, Any],
    *,
    uid: str,
    family: str,
    asset_root: Path,
    source_usd: Path,
) -> dict[str, Any]:
    try:
        meters_per_unit = float(inspection["source_meters_per_unit"])
        up_axis = str(inspection["source_up_axis"])
        default_prim = str(inspection["default_prim"])
        dimensions = [float(value) for value in inspection["dimensions_m"]]
        anchor = [float(value) for value in inspection["anchor_m"]]
        mesh_count = int(inspection["mesh_prim_count"])
        point_count = int(inspection["geometry_point_count"])
        material_count = int(inspection["material_prim_count"])
        bound_count = int(inspection["bound_material_prim_count"])
    except (KeyError, TypeError, ValueError) as exc:
        raise CommunityBuildingAssetError(
            f"{uid} ({family}) converted USD inspection is incomplete"
        ) from exc
    if (
        not math.isfinite(meters_per_unit)
        or not 0.000001 <= meters_per_unit <= 1000.0
        or up_axis not in {"Y", "Z"}
        or not default_prim.startswith("/")
        or len(dimensions) != 3
        or len(anchor) != 3
        or any(not math.isfinite(value) for value in (*dimensions, *anchor))
    ):
        raise CommunityBuildingAssetError(
            f"{uid} ({family}) converted USD inspection has invalid spatial "
            "metadata"
        )
    unit_scale_correction = _UNIT_SCALE_CORRECTIONS.get(uid, 1.0)
    dimensions = [value * unit_scale_correction for value in dimensions]
    anchor = [value * unit_scale_correction for value in anchor]
    horizontal_min, horizontal_max, vertical_min, vertical_max = (
        _DIMENSION_LIMITS_M[family]
    )
    if (
        not horizontal_min <= dimensions[0] <= horizontal_max
        or not horizontal_min <= dimensions[1] <= horizontal_max
        or not vertical_min <= dimensions[2] <= vertical_max
    ):
        raise CommunityBuildingAssetError(
            f"{uid} ({family}) building dimensions are implausible in metres: "
            f"{dimensions}"
        )
    if (
        mesh_count < 1
        or point_count < 4
        or material_count < 1
        or bound_count < mesh_count
        or list(inspection.get("unresolved_dependencies") or [])
    ):
        raise CommunityBuildingAssetError(
            f"{uid} ({family}) converted USD failed mesh/material validation"
        )
    dependencies: list[Path] = []
    for raw in inspection.get("dependency_paths") or []:
        path = Path(raw).resolve()
        if (
            not path.is_file()
            or path.is_symlink()
            or not _inside(asset_root, path)
        ):
            raise CommunityBuildingAssetError(
                f"{uid} ({family}) USD dependency is not standalone: {path}"
            )
        dependencies.append(path)
    if source_usd.resolve() not in dependencies:
        dependencies.append(source_usd.resolve())
    dependencies = sorted(set(dependencies))
    texture_paths = [
        path
        for path in dependencies
        if path.suffix.casefold() in _TEXTURE_SUFFIXES
    ]
    if not texture_paths:
        raise CommunityBuildingAssetError(
            f"{uid} ({family}) converted USD has no locked texture"
        )
    return {
        "source_meters_per_unit": meters_per_unit,
        "source_up_axis": up_axis,
        "unit_scale_correction": unit_scale_correction,
        "default_prim": default_prim,
        "dimensions_m": dimensions,
        "anchor_m": anchor,
        "mesh_prim_count": mesh_count,
        "geometry_point_count": point_count,
        "material_prim_count": material_count,
        "bound_material_prim_count": bound_count,
        "dependency_paths": dependencies,
        "texture_paths": texture_paths,
    }


def _wrapper_text(
    *,
    source: Path,
    wrapper: Path,
    metadata: Mapping[str, Any],
    inspection: Mapping[str, Any],
    source_glb_sha256: str,
) -> str:
    reference = os.path.relpath(source, wrapper.parent).replace("\\", "/")
    if "@" in reference or "\r" in reference or "\n" in reference:
        raise CommunityBuildingAssetError("USD wrapper reference is unsafe")
    source_uri = str(metadata["source_uri"]).replace("\\", "\\\\").replace('"', '\\"')
    attribution = str(metadata["attribution_notice"]).replace(
        "\\", "\\\\"
    ).replace('"', '\\"')
    anchor = inspection["anchor_m"]
    meters_per_unit = float(inspection["source_meters_per_unit"])
    unit_scale_correction = float(inspection["unit_scale_correction"])
    up_axis = str(inspection["source_up_axis"])
    rotation = (
        "        double xformOp:rotateX = 90\n" if up_axis == "Y" else ""
    )
    order = (
        '["xformOp:rotateX", "xformOp:scale"]'
        if up_axis == "Y"
        else '["xformOp:scale"]'
    )
    return f'''#usda 1.0
(
    defaultPrim = "Asset"
    metersPerUnit = 1
    upAxis = "Z"
    customLayerData = {{
        string fireviewer_attribution = "{attribution}"
        string fireviewer_converter = "{CONVERTER_ID}"
        string fireviewer_source_glb_sha256 = "{source_glb_sha256}"
        string fireviewer_source_uri = "{source_uri}"
    }}
)
def Xform "Asset"
{{
    double3 xformOp:translate = ({-float(anchor[0]):.12g}, {-float(anchor[1]):.12g}, {-float(anchor[2]):.12g})
    uniform token[] xformOpOrder = ["xformOp:translate"]
    def Xform "Source" (
        prepend references = @{reference}@
    )
    {{
{rotation}        float3 xformOp:scale = ({meters_per_unit * unit_scale_correction:.12g}, {meters_per_unit * unit_scale_correction:.12g}, {meters_per_unit * unit_scale_correction:.12g})
        uniform token[] xformOpOrder = {order}
    }}
}}
'''


def _manifest_header(payload: Mapping[str, Any]) -> None:
    if payload.get("schema_version") != MANIFEST_SCHEMA_VERSION:
        raise CommunityBuildingAssetError(
            f"manifest schema_version must be {MANIFEST_SCHEMA_VERSION}"
        )
    if payload.get("profile") != MANIFEST_PROFILE:
        raise CommunityBuildingAssetError(
            f"manifest profile must be {MANIFEST_PROFILE}"
        )
    if payload.get("family_minimums") != PHOTOREAL_FAMILY_MINIMUMS:
        raise CommunityBuildingAssetError("manifest family minimums were weakened")
    if payload.get("library_policy") != PHOTOREAL_LIBRARY_POLICY:
        raise CommunityBuildingAssetError("manifest library policy was weakened")
    environment = payload.get("environment")
    if not isinstance(environment, Mapping) or set(environment) != {
        "vegetation",
        "buildings",
    }:
        raise CommunityBuildingAssetError(
            "manifest environment must contain vegetation and buildings"
        )
    for kind, family_minimums in PHOTOREAL_FAMILY_MINIMUMS.items():
        families = environment.get(kind)
        if not isinstance(families, Mapping) or set(families) != set(
            family_minimums
        ):
            raise CommunityBuildingAssetError(
                f"manifest environment.{kind} family tree is malformed"
            )
        if any(not isinstance(families[family], list) for family in family_minimums):
            raise CommunityBuildingAssetError(
                f"manifest environment.{kind} families must be lists"
            )
    discovery = payload.get("discovery")
    if (
        not isinstance(discovery, Mapping)
        or discovery.get("mode")
        != "materialized_photoreal_asset_library_v3"
    ):
        raise CommunityBuildingAssetError(
            "community assets may only augment the materialized v3 manifest"
        )


def _relative_below(path: Path, root: Path, *, label: str) -> PurePosixPath:
    if not _inside(root, path):
        raise CommunityBuildingAssetError(f"{label} escaped the production volume")
    return PurePosixPath(path.resolve().relative_to(root.resolve()).as_posix())


def _build_entry(
    *,
    volume: Path,
    manifest_parent: Path,
    staging_root: Path,
    final_root: Path,
    source_glb: Path,
    source_glb_metrics: Mapping[str, Any],
    metadata: Mapping[str, Any],
    converter: Callable[[Path, Path], None],
    inspector: Callable[[Path, Path, str], Mapping[str, Any]],
) -> dict[str, Any]:
    uid = str(metadata["uid"])
    family = str(metadata["family"])
    asset_stage = staging_root / "assets" / family / uid
    source_usd = asset_stage / "source.usd"
    converter(source_glb, source_usd)
    if not source_usd.is_file() or source_usd.is_symlink():
        raise CommunityBuildingAssetError(
            f"converter did not create the locked USD for {uid}"
        )
    inspection = _validate_inspection(
        inspector(source_usd, asset_stage, family),
        uid=uid,
        family=family,
        asset_root=asset_stage,
        source_usd=source_usd,
    )
    wrapper_stage = staging_root / "wrappers" / family / f"{uid}.usda"
    source_glb_sha = _sha256(source_glb)
    _atomic_write_text(
        wrapper_stage,
        _wrapper_text(
            source=source_usd,
            wrapper=wrapper_stage,
            metadata=metadata,
            inspection=inspection,
            source_glb_sha256=source_glb_sha,
        ),
    )

    def final_path(stage_path: Path) -> Path:
        relative = stage_path.resolve().relative_to(staging_root.resolve())
        return final_root.joinpath(*relative.parts)

    materialized_files = []
    for stage_path in inspection["dependency_paths"]:
        target = final_path(Path(stage_path))
        materialized_files.append(
            {
                "path": _relative_below(
                    target, volume, label=f"{uid} dependency"
                ).as_posix(),
                "sha256": _sha256(Path(stage_path)),
                "size_bytes": Path(stage_path).stat().st_size,
            }
        )
    materialized_files.sort(key=lambda item: str(item["path"]))
    content_lock = hashlib.sha256(
        json.dumps(materialized_files, sort_keys=True).encode("utf-8")
    ).hexdigest()
    source_target = final_path(source_usd)
    wrapper_target = final_path(wrapper_stage)
    provider_hash = _sha256(source_usd)
    visual_metadata = {
        "native_dimensions_m": {
            axis: float(inspection["dimensions_m"][index])
            for index, axis in enumerate(("x", "y", "z"))
        },
        "ground_anchor_m": [0.0, 0.0, 0.0],
        "anchor_validation": {
            "state": "passed",
            "policy": "native_bbox_bottom_center",
        },
        "lod": {
            "state": "passed",
            "strategy": "source_default_only",
            "levels": [str(inspection["default_prim"])],
            "level_count": 1,
        },
        "materials": {
            "state": "passed",
            "material_prim_count": int(inspection["material_prim_count"]),
            "bound_material_prim_count": int(
                inspection["bound_material_prim_count"]
            ),
            "resolved_asset_dependency_count": max(
                0, len(materialized_files) - 1
            ),
            "unresolved_dependencies": [],
            "texture_dependency_count": len(inspection["texture_paths"]),
        },
        "placement": {
            "grounding": "native_anchor",
            "scale_policy": "uniform_only",
            "non_uniform_scale_allowed": False,
            "minimum_uniform_scale": 0.8,
            "maximum_uniform_scale": 1.25,
        },
    }
    family_id = f"buildings.{family}"
    return {
        "asset_id": f"{family_id}:objaverse-{uid}",
        "family": family_id,
        "identity": {
            "source_name": str(metadata["title"]),
            "source_identity": f"objaverse:{uid}",
            "objaverse_uid": uid,
        },
        "path": _relative_below(
            wrapper_target, manifest_parent, label=f"{uid} wrapper"
        ).as_posix(),
        "sha256": _sha256(wrapper_stage),
        "source_cache_path": _relative_below(
            source_target, manifest_parent, label=f"{uid} converted USD"
        ).as_posix(),
        "materialized_files": materialized_files,
        "content_lock_sha256": content_lock,
        "dependency_count": max(0, len(materialized_files) - 1),
        "quality_validation": "native_metadata_passed",
        "placement_validation": "pending_console_review",
        "provenance": {
            "provider": PROVIDER,
            "provider_version": f"uid:{uid}",
            "source_uri": metadata["source_uri"],
            "provider_hash": provider_hash,
            "source_glb_sha256": source_glb_sha,
            "source_glb_size_bytes": source_glb.stat().st_size,
            "source_glb_metrics": dict(source_glb_metrics),
            "unit_scale_correction": float(
                inspection["unit_scale_correction"]
            ),
            "raw_metadata_sha256": metadata["raw_metadata_sha256"],
            "reviewed_selection_name": COMMUNITY_BUILDING_TITLES[uid],
            "attribution": {
                "creator": metadata["creator"],
                "notice": metadata["attribution_notice"],
            },
            "conversion": CONVERTER_ID,
        },
        "license": {
            "id": metadata["license_id"],
            "uri": metadata["license_uri"],
            "redistribution": "cc_by_attribution_required",
        },
        "attribution": {
            "creator": metadata["creator"],
            "notice": metadata["attribution_notice"],
            "source_uri": metadata["source_uri"],
        },
        "source_uri": metadata["source_uri"],
        "provider_hash": provider_hash,
        "provider_version": f"uid:{uid}",
        "provider_size_bytes": source_usd.stat().st_size,
        "source_glb_sha256": source_glb_sha,
        "source_glb_size_bytes": source_glb.stat().st_size,
        "source_meters_per_unit": 1.0,
        "source_up_axis": "Z",
        "provider_source_meters_per_unit": float(
            inspection["source_meters_per_unit"]
        ),
        "provider_source_up_axis": inspection["source_up_axis"],
        "provider_unit_scale_correction": float(
            inspection["unit_scale_correction"]
        ),
        "provider_ground_anchor_m": [
            float(value) for value in inspection["anchor_m"]
        ],
        "provider_metadata_validation_sha256": _canonical_sha256(
            {
                "default_prim": inspection["default_prim"],
                "dimensions_m": inspection["dimensions_m"],
                "anchor_m": inspection["anchor_m"],
                "unit_scale_correction": inspection[
                    "unit_scale_correction"
                ],
                "mesh_prim_count": inspection["mesh_prim_count"],
                "geometry_point_count": inspection["geometry_point_count"],
                "material_prim_count": inspection["material_prim_count"],
                "bound_material_prim_count": inspection[
                    "bound_material_prim_count"
                ],
            }
        ),
        **visual_metadata,
        "metadata_validation_sha256": _canonical_sha256(visual_metadata),
        "thumbnail_path": "",
        "license_id": metadata["license_id"],
        "license_uri": metadata["license_uri"],
    }


def _bundle_identity(
    sources: Mapping[str, Path],
    metadata: Mapping[str, Mapping[str, Any]],
) -> str:
    return _canonical_sha256(
        [
            {
                "uid": uid,
                "family": UID_TO_FAMILY[uid],
                "source_glb_sha256": _sha256(sources[uid]),
                "metadata_sha256": metadata[uid]["raw_metadata_sha256"],
            }
            for uid in sorted(UID_TO_FAMILY)
        ]
    )[:20]


def _validate_receipt(
    receipt: Mapping[str, Any],
    *,
    final_root: Path,
    volume: Path,
    manifest_parent: Path,
    bundle_id: str,
    expected_source_locks: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    if (
        receipt.get("schema_version") != INSTALL_SCHEMA_VERSION
        or receipt.get("state") != INSTALL_STATE
        or receipt.get("bundle_id") != bundle_id
        or receipt.get("converter") != CONVERTER_ID
        or receipt.get("source_count") != len(UID_TO_FAMILY)
    ):
        raise CommunityBuildingAssetError(
            f"existing community building bundle is incompatible: {final_root}"
        )
    source_locks = receipt.get("source_locks")
    if (
        not isinstance(source_locks, list)
        or _canonical_sha256(source_locks)
        != _canonical_sha256(expected_source_locks)
    ):
        raise CommunityBuildingAssetError(
            "community building receipt source locks drifted"
        )
    entries = receipt.get("entries")
    if not isinstance(entries, list) or len(entries) != len(UID_TO_FAMILY):
        raise CommunityBuildingAssetError(
            "community building receipt has an incomplete entry inventory"
        )
    seen_uids: set[str] = set()
    source_locks_by_uid = {
        str(record["uid"]): record for record in expected_source_locks
    }
    for entry in entries:
        if not isinstance(entry, Mapping):
            raise CommunityBuildingAssetError(
                "community building receipt contains a malformed entry"
            )
        identity = entry.get("identity")
        uid = (
            str(identity.get("objaverse_uid", "")).strip()
            if isinstance(identity, Mapping)
            else ""
        )
        family = UID_TO_FAMILY.get(uid)
        expected_asset_id = (
            f"buildings.{family}:objaverse-{uid}" if family is not None else ""
        )
        if (
            family is None
            or uid in seen_uids
            or entry.get("asset_id") != expected_asset_id
            or entry.get("family") != f"buildings.{family}"
        ):
            raise CommunityBuildingAssetError(
                "community building receipt entry identity drifted"
            )
        source_lock = source_locks_by_uid[uid]
        provenance = entry.get("provenance")
        if (
            entry.get("source_glb_sha256") != source_lock["sha256"]
            or entry.get("source_glb_size_bytes") != source_lock["size_bytes"]
            or not isinstance(provenance, Mapping)
            or provenance.get("source_glb_sha256") != source_lock["sha256"]
            or provenance.get("source_glb_size_bytes") != source_lock["size_bytes"]
            or provenance.get("raw_metadata_sha256")
            != source_lock["metadata_sha256"]
        ):
            raise CommunityBuildingAssetError(
                f"community building receipt source provenance drifted: {uid}"
            )
        seen_uids.add(uid)
        manifest_relative = PurePosixPath(str(entry.get("path", "")))
        if (
            manifest_relative.is_absolute()
            or not manifest_relative.parts
            or ".." in manifest_relative.parts
        ):
            raise CommunityBuildingAssetError(
                f"community building wrapper path is unsafe: "
                f"{entry.get('asset_id')}"
            )
        wrapper = manifest_parent.joinpath(*manifest_relative.parts).resolve()
        expected = str(entry.get("sha256", "")).strip().lower()
        if (
            not wrapper.is_file()
            or wrapper.is_symlink()
            or not _inside(volume, wrapper)
            or not _SHA256_RE.fullmatch(expected)
            or _sha256(wrapper) != expected
        ):
            raise CommunityBuildingAssetError(
                f"community building wrapper lock drifted: {entry.get('asset_id')}"
            )
        records = entry.get("materialized_files")
        if not isinstance(records, list) or not records:
            raise CommunityBuildingAssetError(
                f"community building dependency lock is absent: "
                f"{entry.get('asset_id')}"
            )
        verified = []
        for record in records:
            if not isinstance(record, Mapping):
                raise CommunityBuildingAssetError(
                    "community building dependency record is malformed"
                )
            dependency = volume.joinpath(
                *PurePosixPath(str(record.get("path", ""))).parts
            ).resolve()
            expected_sha = str(record.get("sha256", "")).strip().lower()
            if (
                not dependency.is_file()
                or dependency.is_symlink()
                or not _inside(final_root, dependency)
                or _sha256(dependency) != expected_sha
                or dependency.stat().st_size != record.get("size_bytes")
            ):
                raise CommunityBuildingAssetError(
                    f"community building dependency lock drifted: {dependency}"
                )
            verified.append(dict(record))
        if hashlib.sha256(
            json.dumps(verified, sort_keys=True).encode("utf-8")
        ).hexdigest() != entry.get("content_lock_sha256"):
            raise CommunityBuildingAssetError(
                f"community building content lock drifted: {entry.get('asset_id')}"
            )
    if seen_uids != set(UID_TO_FAMILY):
        raise CommunityBuildingAssetError(
            "community building receipt has an incomplete UID inventory"
        )
    return [dict(entry) for entry in entries]


def install_community_building_assets(
    *,
    volume_root: Path,
    manifest_path: Path,
    source_root: Path,
    metadata_path: Path,
    output_root: Path | None = None,
    converter: Callable[[Path, Path], None] = _kit_asset_convert,
    inspector: Callable[
        [Path, Path, str], Mapping[str, Any]
    ] = _inspect_converted_usd,
) -> dict[str, Any]:
    """Convert, validate and atomically merge the reviewed building set."""

    volume = volume_root.resolve()
    manifest = manifest_path.resolve()
    sources_root = source_root.resolve()
    metadata_file = metadata_path.resolve()
    if not volume.is_dir():
        raise CommunityBuildingAssetError(f"volume root is absent: {volume}")
    for label, path in (
        ("manifest", manifest),
        ("source root", sources_root),
        ("metadata", metadata_file),
    ):
        if not _inside(volume, path):
            raise CommunityBuildingAssetError(
                f"{label} must remain inside the production volume"
            )
    initial_manifest_sha = _sha256(manifest)
    payload = _read_json(manifest, label="official SimReady manifest")
    _manifest_header(payload)
    records = _extract_records(
        _read_json(metadata_file, label="community attribution metadata")
    )
    normalized: dict[str, dict[str, Any]] = {}
    source_paths: dict[str, Path] = {}
    source_metrics: dict[str, dict[str, int]] = {}
    source_hashes: set[str] = set()
    for uid, family in UID_TO_FAMILY.items():
        normalized[uid] = _normalized_metadata(
            uid=uid,
            family=family,
            record=records[uid],
        )
        relative = PurePosixPath(normalized[uid]["local_path"])
        source = sources_root.joinpath(*relative.parts).resolve()
        if not _inside(sources_root, source):
            raise CommunityBuildingAssetError(f"{uid} source escaped source_root")
        source_metrics[uid] = _validate_glb(source, uid=uid)
        source_paths[uid] = source
        digest = _sha256(source)
        if digest in source_hashes:
            raise CommunityBuildingAssetError(
                f"{uid} duplicates another reviewed building GLB"
            )
        source_hashes.add(digest)

    bundle_id = _bundle_identity(source_paths, normalized)
    source_locks = [
        {
            "uid": uid,
            "family": UID_TO_FAMILY[uid],
            "sha256": _sha256(source_paths[uid]),
            "size_bytes": source_paths[uid].stat().st_size,
            "metadata_sha256": normalized[uid]["raw_metadata_sha256"],
        }
        for uid in sorted(UID_TO_FAMILY)
    ]
    final_root = (
        output_root.resolve()
        if output_root is not None
        else manifest.parent / "community-building-assets" / bundle_id
    )
    if not _inside(manifest.parent, final_root):
        raise CommunityBuildingAssetError(
            "community asset output must remain below the manifest directory"
        )
    receipt_path = final_root / "install-receipt.json"
    entries: list[dict[str, Any]]
    reused = False
    if final_root.exists():
        receipt_sha256 = _sha256(receipt_path)
        receipt = _read_json(
            receipt_path, label="existing community building receipt"
        )
        entries = _validate_receipt(
            receipt,
            final_root=final_root,
            volume=volume,
            manifest_parent=manifest.parent,
            bundle_id=bundle_id,
            expected_source_locks=source_locks,
        )
        if _sha256(receipt_path) != receipt_sha256:
            raise CommunityBuildingAssetError(
                "community building receipt changed while it was validated"
            )
        reused = True
    else:
        staging = final_root.parent / (
            f".{final_root.name}.staging-{uuid.uuid4().hex}"
        )
        if staging.exists():
            raise CommunityBuildingAssetError(
                f"community staging path unexpectedly exists: {staging}"
            )
        staging.mkdir(parents=True)
        try:
            entries = [
                _build_entry(
                    volume=volume,
                    manifest_parent=manifest.parent,
                    staging_root=staging,
                    final_root=final_root,
                    source_glb=source_paths[uid],
                    source_glb_metrics=source_metrics[uid],
                    metadata=normalized[uid],
                    converter=converter,
                    inspector=inspector,
                )
                for uid in sorted(UID_TO_FAMILY)
            ]
            receipt = {
                "schema_version": INSTALL_SCHEMA_VERSION,
                "state": INSTALL_STATE,
                "bundle_id": bundle_id,
                "converter": CONVERTER_ID,
                "source_count": len(entries),
                "entries": entries,
                "source_locks": source_locks,
            }
            _atomic_write_json(staging / receipt_path.name, receipt)
            final_root.parent.mkdir(parents=True, exist_ok=True)
            os.replace(staging, final_root)
            receipt_sha256 = _sha256(receipt_path)
        except Exception:
            if staging.exists():
                shutil.rmtree(staging)
            raise

    augmented = json.loads(json.dumps(payload))
    buildings = augmented["environment"]["buildings"]
    by_asset_id = {
        str(item.get("asset_id", "")): item
        for family_entries in buildings.values()
        for item in family_entries
        if isinstance(item, Mapping)
    }
    for entry in entries:
        asset_id = str(entry["asset_id"])
        existing = by_asset_id.get(asset_id)
        if existing is not None:
            if _canonical_sha256(existing) != _canonical_sha256(entry):
                raise CommunityBuildingAssetError(
                    f"manifest already contains a conflicting {asset_id}"
                )
            continue
        family = str(entry["family"]).split(".", 1)[1]
        buildings[family].append(entry)
        by_asset_id[asset_id] = entry

    missing_environment = [
        f"{kind}.{family}"
        for kind, family_minimums in PHOTOREAL_FAMILY_MINIMUMS.items()
        for family, minimum in family_minimums.items()
        if len(augmented["environment"][kind][family]) < minimum
    ]
    if missing_environment:
        raise CommunityBuildingAssetError(
            "community supplement still cannot complete the photoreal family "
            "contract: " + ", ".join(missing_environment)
        )
    discovery = augmented["discovery"]
    discovery["missing_environment"] = []
    discovery["community_building_supplement"] = {
        "state": INSTALL_STATE,
        "provider": PROVIDER,
        "converter": CONVERTER_ID,
        "bundle_id": bundle_id,
        "asset_count": len(entries),
        "objaverse_uids": sorted(UID_TO_FAMILY),
        "receipt": receipt_path.relative_to(manifest.parent).as_posix(),
        "receipt_sha256": receipt_sha256,
    }

    manifest_changed = _canonical_sha256(payload) != _canonical_sha256(augmented)
    if manifest_changed:
        if _sha256(manifest) != initial_manifest_sha:
            raise CommunityBuildingAssetError(
                "SimReady manifest changed while community assets were converting"
            )
        if _sha256(receipt_path) != receipt_sha256:
            raise CommunityBuildingAssetError(
                "community building receipt changed before manifest attachment"
            )
        _atomic_write_json(manifest, augmented)
    final_manifest_sha = _sha256(manifest)
    result = {
        "schema_version": INSTALL_SCHEMA_VERSION,
        "state": INSTALL_STATE,
        "manifest": str(manifest),
        "manifest_sha256": final_manifest_sha,
        "bundle_root": str(final_root),
        "bundle_id": bundle_id,
        "receipt": str(receipt_path),
        "receipt_sha256": receipt_sha256,
        "asset_count": len(entries),
        "family_counts": {
            family: sum(
                1 for entry in entries if entry["family"] == f"buildings.{family}"
            )
            for family in COMMUNITY_BUILDING_UIDS
        },
        "reused": reused,
        "reattached": reused and manifest_changed,
        "manifest_changed": manifest_changed,
    }
    _atomic_write_json(
        manifest.with_name("community-building-install-report.json"),
        result,
    )
    return result


def _start_isaac_runtime() -> object | None:
    try:
        import omni.kit.app

        app = omni.kit.app.get_app()
        is_running = getattr(app, "is_running", None)
        if app is not None and (
            not callable(is_running) or bool(is_running())
        ):
            return None
    except (ImportError, RuntimeError):
        pass
    try:
        from isaacsim import SimulationApp
    except ImportError as exc:  # pragma: no cover - pod-only gate
        raise CommunityBuildingAssetError(
            "run this command with Isaac Sim python.sh or an active Kit app"
        ) from exc
    return SimulationApp({"headless": True})


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Convert and install the reviewed CC-BY Objaverse buildings "
            "into FireViewer's materialized SimReady manifest."
        )
    )
    parser.add_argument("--volume-root", required=True, type=Path)
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--source-root", required=True, type=Path)
    parser.add_argument("--metadata", required=True, type=Path)
    parser.add_argument("--output-root", type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    runtime = _start_isaac_runtime()
    try:
        result = install_community_building_assets(
            volume_root=args.volume_root,
            manifest_path=args.manifest,
            source_root=args.source_root,
            metadata_path=args.metadata,
            output_root=args.output_root,
        )
    except CommunityBuildingAssetError as exc:
        print(
            f"COMMUNITY_BUILDING_ASSETS_FAILED: {exc}",
            file=sys.stderr,
            flush=True,
        )
        if runtime is not None:
            # Fast Kit shutdown exits zero before Python can propagate a CLI
            # failure. Staging cleanup is already complete at this boundary.
            os._exit(1)
        return 1
    print(
        json.dumps(result, ensure_ascii=False, sort_keys=True),
        flush=True,
    )
    if runtime is not None:
        runtime.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "COMMUNITY_BUILDING_GLB_LOCKS",
    "COMMUNITY_BUILDING_TITLES",
    "COMMUNITY_BUILDING_UIDS",
    "CommunityBuildingAssetError",
    "INSTALL_STATE",
    "install_community_building_assets",
    "main",
]
