"""Deterministic, composition-locked RGB restyling for FireViewer captures.

The source capture is immutable.  This module prepares a single-image ComfyUI
job and admits a derived RGB only after co-registration checks pass.  Depth,
normals, masks, camera data, geolocation and fire/smoke metadata are never
rewritten or regenerated by this workflow.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import re
import shutil
import sys
import tempfile
import time
import urllib.parse
import urllib.request
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

import numpy as np
from PIL import Image


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CONTRACT_PATH = PROJECT_ROOT / "config" / "rgb-restyle-photoreal-v1.json"
DEFAULT_MODEL_ROOT = Path(os.environ.get("FW_COMFY_MODEL_ROOT", r"D:\AI\Models\ComfyUI"))
DEFAULT_COMFY_SERVER = "http://127.0.0.1:8188"
SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
PLACEHOLDERS = {
    "__INPUT_IMAGE__",
    "__POSITIVE_PROMPT__",
    "__NEGATIVE_PROMPT__",
    "__SEED__",
    "__WIDTH__",
    "__HEIGHT__",
    "__OUTPUT_PREFIX__",
}


class RestyleContractError(RuntimeError):
    """Raised when a source, workflow or contract violates the lock."""


class AdmissionRejected(RestyleContractError):
    """Raised when a generated candidate fails composition admission."""

    def __init__(self, report: Mapping[str, Any]) -> None:
        self.report = dict(report)
        failed = [name for name, passed in report.get("gates", {}).items() if not passed]
        super().__init__("restyle candidate rejected: " + ", ".join(failed))


@dataclass(frozen=True)
class CaptureInventory:
    capture_dir: Path
    capture_id: str
    width_px: int
    height_px: int
    source_files: dict[str, dict[str, Any]]
    source_binding_sha256: str
    expected_fire_visible: bool
    sample_kind: str
    protected_pixel_count: int
    fire_pixel_count: int
    smoke_pixel_count: int
    target_witness: dict[str, Any]

    def as_dict(self, *, include_local_path: bool = False) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "schema": "fireviewer.rgb-restyle.capture-inventory.v1",
            "capture_id": self.capture_id,
            "width_px": self.width_px,
            "height_px": self.height_px,
            "source_files": self.source_files,
            "source_binding_sha256": self.source_binding_sha256,
            "expected_fire_visible": self.expected_fire_visible,
            "sample_kind": self.sample_kind,
            "protected_pixel_count": self.protected_pixel_count,
            "fire_pixel_count": self.fire_pixel_count,
            "smoke_pixel_count": self.smoke_pixel_count,
            "target_witness": self.target_witness,
        }
        if include_local_path:
            payload["capture_dir"] = str(self.capture_dir)
        return payload


def canonical_json_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        while chunk := source.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def _load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RestyleContractError(f"invalid JSON file {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise RestyleContractError(f"JSON root must be an object: {path}")
    return value


def _write_json_atomic(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + f".tmp-{os.getpid()}")
    temporary.write_bytes(canonical_json_bytes(value) + b"\n")
    os.replace(temporary, path)


def _file_record(path: Path) -> dict[str, Any]:
    return {
        "sha256": sha256_file(path),
        "size_bytes": path.stat().st_size,
    }


def _version_tuple(value: str) -> tuple[int, ...]:
    numbers = re.findall(r"\d+", value)
    return tuple(int(number) for number in numbers[:3])


def _merge_contract(base: Mapping[str, Any], overlay: Mapping[str, Any]) -> dict[str, Any]:
    merged: dict[str, Any] = dict(base)
    for key, value in overlay.items():
        if key == "extends":
            continue
        if isinstance(value, Mapping) and isinstance(merged.get(key), Mapping):
            merged[key] = _merge_contract(merged[key], value)
        else:
            merged[key] = value
    return merged


def load_contract(path: Path = DEFAULT_CONTRACT_PATH) -> dict[str, Any]:
    resolved = path.resolve()
    overlay = _load_json(resolved)
    parent_hash: str | None = None
    if isinstance(overlay.get("extends"), str):
        parent = (resolved.parent / overlay["extends"]).resolve()
        if parent.parent != resolved.parent or not parent.is_file():
            raise RestyleContractError("contract extension must be a sibling JSON contract")
        base = load_contract(parent)
        parent_hash = str(base["_contract_sha256"])
        contract = _merge_contract(
            {key: value for key, value in base.items() if not key.startswith("_")}, overlay
        )
    else:
        contract = overlay
    if contract.get("schema") != "fireviewer.rgb-restyle.contract.v1":
        raise RestyleContractError("unsupported RGB restyle contract schema")
    if contract.get("status") not in {"locked-pilot-only", "locked-batch-validation"}:
        raise RestyleContractError("the RGB restyle contract is not locked for controlled use")
    source = contract.get("source_contract")
    engine = contract.get("engine")
    lock = contract.get("composition_lock")
    if not all(isinstance(value, dict) for value in (source, engine, lock)):
        raise RestyleContractError("contract source, engine and composition lock are required")
    if source.get("overwrite_source") is not False:
        raise RestyleContractError("source overwrite must remain disabled")
    if engine.get("control_adapters") or engine.get("lora_adapters"):
        raise RestyleContractError("v1 forbids ControlNet and LoRA adapters")
    workflow_relative = engine.get("api_workflow")
    workflow_sha = engine.get("api_workflow_sha256")
    if not isinstance(workflow_relative, str) or not SHA256_PATTERN.fullmatch(str(workflow_sha)):
        raise RestyleContractError("workflow path and SHA-256 are required")
    workflow_path = (PROJECT_ROOT / workflow_relative).resolve()
    if not workflow_path.is_file():
        raise RestyleContractError(f"locked workflow is missing: {workflow_path}")
    if sha256_file(workflow_path) != workflow_sha:
        raise RestyleContractError("locked ComfyUI workflow SHA-256 mismatch")
    for model in engine.get("models", []):
        if not isinstance(model, dict):
            raise RestyleContractError("invalid model lock entry")
        if not SHA256_PATTERN.fullmatch(str(model.get("sha256", ""))):
            raise RestyleContractError(f"invalid model SHA-256 for {model.get('role')}")
        if not isinstance(model.get("size_bytes"), int) or model["size_bytes"] <= 0:
            raise RestyleContractError(f"invalid model size for {model.get('role')}")
    validate_workflow_structure(_load_json(workflow_path), contract)
    contract["_contract_sha256"] = sha256_bytes(
        canonical_json_bytes(
            {
                "overlay_sha256": sha256_file(resolved),
                "parent_contract_sha256": parent_hash,
                "resolved_contract": contract,
            }
        )
    )
    contract["_contract_path"] = str(resolved)
    contract["_workflow_path"] = str(workflow_path)
    return contract


def validate_workflow_structure(
    workflow: Mapping[str, Any], contract: Mapping[str, Any]
) -> None:
    if not workflow:
        raise RestyleContractError("ComfyUI workflow is empty")
    classes: list[str] = []
    for node_id, node in workflow.items():
        if not isinstance(node_id, str) or not isinstance(node, dict):
            raise RestyleContractError("ComfyUI API workflow nodes must be string-keyed objects")
        class_type = node.get("class_type")
        if not isinstance(class_type, str) or not isinstance(node.get("inputs"), dict):
            raise RestyleContractError(f"invalid ComfyUI node {node_id}")
        classes.append(class_type)
    required = set(contract["engine"]["required_node_classes"])
    if set(classes) != required:
        missing = sorted(required - set(classes))
        unexpected = sorted(set(classes) - required)
        raise RestyleContractError(
            f"workflow node lock mismatch; missing={missing}, unexpected={unexpected}"
        )
    by_class: dict[str, list[Mapping[str, Any]]] = {}
    for node in workflow.values():
        by_class.setdefault(node["class_type"], []).append(node)
    engine = contract["engine"]
    if by_class["UNETLoader"][0]["inputs"].get("unet_name") != engine["models"][0]["comfy_name"]:
        raise RestyleContractError("workflow diffusion model differs from the contract")
    if by_class["KSamplerSelect"][0]["inputs"].get("sampler_name") != engine["sampler"]:
        raise RestyleContractError("workflow sampler differs from the contract")
    if by_class["Flux2Scheduler"][0]["inputs"].get("steps") != engine["steps"]:
        raise RestyleContractError("workflow step count differs from the contract")
    if float(by_class["CFGGuider"][0]["inputs"].get("cfg")) != float(engine["cfg"]):
        raise RestyleContractError("workflow CFG differs from the contract")
    serialized = json.dumps(workflow, ensure_ascii=False)
    present = {placeholder for placeholder in PLACEHOLDERS if placeholder in serialized}
    if present != PLACEHOLDERS:
        raise RestyleContractError(
            f"workflow placeholders differ from lock: {sorted(present)}"
        )


def _load_npz_array(path: Path) -> np.ndarray:
    try:
        with np.load(path, allow_pickle=False) as archive:
            if "data" in archive.files:
                array = archive["data"]
            elif len(archive.files) == 1:
                array = archive[archive.files[0]]
            else:
                raise RestyleContractError(f"ambiguous NPZ arrays in {path.name}")
            return np.asarray(array).copy()
    except (OSError, ValueError) as exc:
        raise RestyleContractError(f"cannot read {path}: {exc}") from exc


def _mask(path: Path, shape: tuple[int, int]) -> np.ndarray:
    value = _load_npz_array(path)
    if value.shape != shape:
        raise RestyleContractError(
            f"mask shape mismatch for {path.name}: {value.shape} != {shape}"
        )
    return value != 0


def _resolution_from_plan(plan: Mapping[str, Any]) -> tuple[int, int] | None:
    value = plan.get("image_resolution_px")
    if isinstance(value, list) and len(value) == 2:
        return int(value[0]), int(value[1])
    if isinstance(value, dict):
        width = value.get("width") or value.get("width_px")
        height = value.get("height") or value.get("height_px")
        if width is not None and height is not None:
            return int(width), int(height)
    return None


def _target_witness(
    plan: Mapping[str, Any], targets: Mapping[str, Any]
) -> dict[str, Any]:
    return {
        "camera_id": plan.get("camera_id"),
        "camera_position_local_m": plan.get("camera_position_local_m"),
        "camera_position_l93_ngf_ign69_m": plan.get("camera_position_l93_ngf_ign69_m"),
        "camera_orientation_quat_wxyz": plan.get("camera_orientation_quat_wxyz"),
        "camera_orientation_yaw_pitch_roll_degrees": plan.get(
            "camera_orientation_yaw_pitch_roll_degrees"
        ),
        "focal_length_mm": plan.get("focal_length_mm"),
        "horizontal_fov_degrees": plan.get("horizontal_fov_degrees"),
        "captured_at_utc": plan.get("captured_at_utc"),
        "simulation_time": targets.get("simulation_time"),
        "nearest_flame": targets.get("nearest_flame"),
        "nearest_smoke": targets.get("nearest_smoke"),
        "visible_flame_points_local_m": targets.get("visible_flame_points_local_m"),
        "smoke_source_points_local_m": targets.get("smoke_source_points_local_m"),
    }


def inventory_capture(
    capture_dir: Path,
    contract: Mapping[str, Any] | None = None,
) -> CaptureInventory:
    capture = capture_dir.resolve()
    active_contract = dict(contract) if contract is not None else load_contract()
    if not capture.is_dir():
        raise RestyleContractError(f"capture directory does not exist: {capture}")
    required = tuple(active_contract["source_contract"]["required_files"])
    missing = [name for name in required if not (capture / name).is_file()]
    if missing:
        raise RestyleContractError(f"capture is missing required files: {missing}")

    try:
        with Image.open(capture / "rgb.png") as source:
            source.load()
            width, height = source.size
            if source.mode not in {"RGB", "RGBA"}:
                raise RestyleContractError(f"unsupported source RGB mode: {source.mode}")
    except OSError as exc:
        raise RestyleContractError(f"cannot decode source RGB: {exc}") from exc
    if width % 16 or height % 16:
        raise RestyleContractError("FLUX.2 input dimensions must be multiples of 16")

    plan = _load_json(capture / "capture-plan.json")
    targets = _load_json(capture / "training-targets.json")
    capture_id = plan.get("capture_id")
    if not isinstance(capture_id, str) or not capture_id:
        raise RestyleContractError("capture-plan.json has no stable capture_id")
    if targets.get("capture_id") != capture_id:
        raise RestyleContractError("capture-plan and training-targets capture_id mismatch")
    plan_resolution = _resolution_from_plan(plan)
    if plan_resolution is not None and plan_resolution != (width, height):
        raise RestyleContractError(
            f"RGB resolution {width}x{height} differs from capture plan {plan_resolution}"
        )

    shape = (height, width)
    depth = _load_npz_array(capture / "depth_distance_to_camera_m.npz")
    normals = _load_npz_array(capture / "normals_replicator.npz")
    semantic = _load_npz_array(capture / "semantic_ids.npz")
    instance = _load_npz_array(capture / "instance_ids.npz")
    if depth.shape != shape or semantic.shape != shape or instance.shape != shape:
        raise RestyleContractError("depth, semantic or instance raster is not co-registered")
    if normals.shape[:2] != shape or normals.ndim != 3 or normals.shape[2] < 3:
        raise RestyleContractError("normal raster is not co-registered")
    finite_depth = np.isfinite(depth)
    positive_depth = finite_depth & (depth > 0)
    # Replicator uses +inf for camera rays that do not hit scene geometry
    # (typically sky/background). Keep that explicit no-hit sentinel, while
    # rejecting NaN, -inf and invalid finite distances.
    if (
        not np.any(positive_depth)
        or np.any(np.isnan(depth))
        or np.any(np.isneginf(depth))
        or np.any(finite_depth & (depth <= 0))
    ):
        raise RestyleContractError(
            "depth raster must contain positive finite distances and may use only +inf for no-hit pixels"
        )

    protected_masks = [
        _mask(capture / name, shape)
        for name in active_contract["source_contract"]["protected_masks"]
    ]
    protected = np.logical_or.reduce(protected_masks)
    flame = _mask(capture / "flame_mask.npz", shape)
    smoke = _mask(capture / "smoke_mask.npz", shape)
    expected_fire = bool(
        plan.get("expected_fire_visible", targets.get("expected_fire_in_frame", False))
    )
    if "expected_fire_visible" in plan and "expected_fire_in_frame" in targets:
        if bool(plan["expected_fire_visible"]) != bool(targets["expected_fire_in_frame"]):
            raise RestyleContractError("fire visibility expectation differs between metadata files")
    if expected_fire and not np.any(flame | smoke):
        raise RestyleContractError("positive capture has no flame or smoke pixels")

    source_files: dict[str, dict[str, Any]] = {}
    for path in sorted((path for path in capture.iterdir() if path.is_file()), key=lambda item: item.name):
        source_files[path.name] = _file_record(path)
    modality_hashes = targets.get("modality_sha256")
    if not isinstance(modality_hashes, dict):
        raise RestyleContractError("training-targets has no modality SHA-256 map")
    for name, expected_sha in modality_hashes.items():
        if not isinstance(name, str) or not isinstance(expected_sha, str):
            raise RestyleContractError("invalid modality SHA-256 entry")
        path = capture / name
        if not path.is_file():
            raise RestyleContractError(f"metadata references missing modality: {name}")
        actual = source_files.get(name, _file_record(path))["sha256"]
        if actual != expected_sha.lower():
            raise RestyleContractError(f"source modality SHA-256 mismatch: {name}")

    binding = sha256_bytes(canonical_json_bytes(source_files))
    return CaptureInventory(
        capture_dir=capture,
        capture_id=capture_id,
        width_px=width,
        height_px=height,
        source_files=source_files,
        source_binding_sha256=binding,
        expected_fire_visible=expected_fire,
        sample_kind=str(targets.get("sample_kind", plan.get("sample_kind", "unknown"))),
        protected_pixel_count=int(np.count_nonzero(protected)),
        fire_pixel_count=int(np.count_nonzero(flame)),
        smoke_pixel_count=int(np.count_nonzero(smoke)),
        target_witness=_target_witness(plan, targets),
    )


def derive_seed(source_rgb_sha256: str, capture_id: str, workflow_sha256: str) -> int:
    if not SHA256_PATTERN.fullmatch(source_rgb_sha256):
        raise RestyleContractError("invalid source RGB SHA-256 for seed derivation")
    if not SHA256_PATTERN.fullmatch(workflow_sha256):
        raise RestyleContractError("invalid workflow SHA-256 for seed derivation")
    value = f"{source_rgb_sha256}:{capture_id}:{workflow_sha256}".encode("utf-8")
    return int.from_bytes(hashlib.sha256(value).digest()[:8], "big", signed=False)


def _replace_placeholders(value: Any, replacements: Mapping[str, Any]) -> Any:
    if isinstance(value, dict):
        return {key: _replace_placeholders(item, replacements) for key, item in value.items()}
    if isinstance(value, list):
        return [_replace_placeholders(item, replacements) for item in value]
    if isinstance(value, str) and value in replacements:
        return replacements[value]
    return value


def render_workflow(
    contract: Mapping[str, Any],
    inventory: CaptureInventory,
    *,
    input_name: str,
    output_prefix: str,
) -> tuple[dict[str, Any], int]:
    workflow = _load_json(Path(str(contract["_workflow_path"])))
    seed = derive_seed(
        inventory.source_files["rgb.png"]["sha256"],
        inventory.capture_id,
        contract["engine"]["api_workflow_sha256"],
    )
    replacements: dict[str, Any] = {
        "__INPUT_IMAGE__": input_name,
        "__POSITIVE_PROMPT__": contract["prompt"]["positive"],
        "__NEGATIVE_PROMPT__": contract["prompt"]["negative"],
        "__SEED__": seed,
        "__WIDTH__": inventory.width_px,
        "__HEIGHT__": inventory.height_px,
        "__OUTPUT_PREFIX__": output_prefix,
    }
    rendered = _replace_placeholders(copy.deepcopy(workflow), replacements)
    serialized = json.dumps(rendered, ensure_ascii=False)
    unresolved = [placeholder for placeholder in PLACEHOLDERS if placeholder in serialized]
    if unresolved:
        raise RestyleContractError(f"unresolved workflow placeholders: {unresolved}")
    return rendered, seed


def verify_model_locks(
    contract: Mapping[str, Any], model_root: Path, *, hash_files: bool = True
) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for model in contract["engine"]["models"]:
        path = (model_root / model["comfy_subdir"] / model["comfy_name"]).resolve()
        if not path.is_file():
            raise RestyleContractError(f"locked ComfyUI model is missing: {path}")
        size = path.stat().st_size
        if size != model["size_bytes"]:
            raise RestyleContractError(f"locked ComfyUI model size mismatch: {path.name}")
        actual_sha = sha256_file(path) if hash_files else None
        if actual_sha is not None and actual_sha != model["sha256"]:
            raise RestyleContractError(f"locked ComfyUI model SHA-256 mismatch: {path.name}")
        records.append(
            {
                "role": model["role"],
                "comfy_subdir": model["comfy_subdir"],
                "comfy_name": model["comfy_name"],
                "size_bytes": size,
                "sha256": actual_sha or model["sha256"],
                "hash_verified": actual_sha is not None,
                "license_status": model["license_status"],
            }
        )
    return records


def prepare_job(
    capture_dir: Path,
    job_root: Path,
    *,
    contract_path: Path = DEFAULT_CONTRACT_PATH,
    model_root: Path = DEFAULT_MODEL_ROOT,
    hash_models: bool = True,
) -> tuple[Path, dict[str, Any]]:
    contract = load_contract(contract_path)
    inventory = inventory_capture(capture_dir, contract)
    job_id = sha256_bytes(
        canonical_json_bytes(
            {
                "capture_id": inventory.capture_id,
                "source_binding_sha256": inventory.source_binding_sha256,
                "contract_sha256": contract["_contract_sha256"],
            }
        )
    )[:24]
    subfolder = f"fireviewer_rgb_restyle/{job_id}"
    input_name = f"{subfolder}/rgb.png"
    output_prefix = candidate_output_prefix(job_id)
    prompt, seed = render_workflow(
        contract,
        inventory,
        input_name=input_name,
        output_prefix=output_prefix,
    )
    model_records = verify_model_locks(contract, model_root, hash_files=hash_models)
    job_dir = (job_root.resolve() / job_id)
    if job_dir.exists():
        raise RestyleContractError(f"immutable job directory already exists: {job_dir}")
    job_dir.mkdir(parents=True)
    prompt_path = job_dir / "prompt.api.json"
    _write_json_atomic(prompt_path, prompt)
    manifest = {
        "schema": "fireviewer.rgb-restyle.job.v1",
        "job_id": job_id,
        "state": "prepared-not-submitted",
        "capture": inventory.as_dict(include_local_path=True),
        "source_rgb_path": str(inventory.capture_dir / "rgb.png"),
        "contract_path": str(Path(str(contract["_contract_path"]))),
        "contract_sha256": contract["_contract_sha256"],
        "workflow_sha256": contract["engine"]["api_workflow_sha256"],
        "prompt_path": str(prompt_path),
        "prompt_sha256": sha256_file(prompt_path),
        "seed": seed,
        "comfy_upload": {
            "filename": "rgb.png",
            "subfolder": subfolder,
            "type": "input",
        },
        "comfy_output_prefix": output_prefix,
        "model_locks": model_records,
        "release_gate": contract["release_gate"],
        "gpu_workload_submitted": False,
    }
    manifest_path = job_dir / "job-manifest.json"
    _write_json_atomic(manifest_path, manifest)
    return manifest_path, manifest


def candidate_output_prefix(job_id: str, attempt: int = 0) -> str:
    """Return a globally unambiguous ComfyUI output stem for one attempt."""
    if not re.fullmatch(r"[0-9a-f]{24}", job_id):
        raise RestyleContractError(f"invalid restyle job id: {job_id!r}")
    if attempt < 0:
        raise RestyleContractError("restyle attempt must be non-negative")
    return (
        f"fireviewer_rgb_restyle/{job_id}/"
        f"candidate-{job_id}-attempt-{attempt:02d}"
    )


def derive_attempt_seed(base_seed: int, attempt: int) -> int:
    """Derive a repeatable non-identical seed for a rejected generation."""
    if attempt < 0:
        raise RestyleContractError("restyle attempt must be non-negative")
    if attempt == 0:
        return int(base_seed)
    return int.from_bytes(
        hashlib.sha256(f"fireviewer-restyle:{base_seed}:attempt:{attempt}".encode("ascii")).digest()[:8],
        "big",
        signed=False,
    )


def _dilate(mask: np.ndarray, radius: int) -> np.ndarray:
    result = np.asarray(mask, dtype=bool).copy()
    if radius <= 0:
        return result
    for _ in range(radius):
        padded = np.pad(result, 1, mode="constant", constant_values=False)
        expanded = np.zeros_like(result)
        for dy in range(3):
            for dx in range(3):
                expanded |= padded[dy : dy + result.shape[0], dx : dx + result.shape[1]]
        result = expanded
    return result


def build_protected_mask(
    capture_dir: Path,
    contract: Mapping[str, Any],
    shape: tuple[int, int],
) -> np.ndarray:
    masks = [
        _mask(capture_dir / name, shape)
        for name in contract["source_contract"]["protected_masks"]
    ]
    return np.logical_or.reduce(masks)


def composite_protected_pixels(
    source_rgb: np.ndarray,
    candidate_rgb: np.ndarray,
    protected_core: np.ndarray,
    feather_radius_px: int,
) -> np.ndarray:
    if source_rgb.shape != candidate_rgb.shape or source_rgb.shape[:2] != protected_core.shape:
        raise RestyleContractError("protected compositing shapes differ")
    source = source_rgb.astype(np.float32)
    output = candidate_rgb.astype(np.float32).copy()
    previous = protected_core.copy()
    for distance in range(1, feather_radius_px + 1):
        expanded = _dilate(protected_core, distance)
        ring = expanded & ~previous
        source_weight = (feather_radius_px - distance + 1) / (feather_radius_px + 1)
        output[ring] = source[ring] * source_weight + output[ring] * (1.0 - source_weight)
        previous = expanded
    output[protected_core] = source[protected_core]
    return np.clip(np.rint(output), 0, 255).astype(np.uint8)


def _luminance(rgb: np.ndarray) -> np.ndarray:
    value = rgb.astype(np.float32) / 255.0
    return value[..., 0] * 0.2126 + value[..., 1] * 0.7152 + value[..., 2] * 0.0722


def _gradient_magnitude(value: np.ndarray) -> np.ndarray:
    padded = np.pad(value.astype(np.float32), 1, mode="edge")
    top_left = padded[:-2, :-2]
    top = padded[:-2, 1:-1]
    top_right = padded[:-2, 2:]
    left = padded[1:-1, :-2]
    right = padded[1:-1, 2:]
    bottom_left = padded[2:, :-2]
    bottom = padded[2:, 1:-1]
    bottom_right = padded[2:, 2:]
    gx = -top_left - 2.0 * left - bottom_left + top_right + 2.0 * right + bottom_right
    gy = -top_left - 2.0 * top - top_right + bottom_left + 2.0 * bottom + bottom_right
    return np.sqrt(gx * gx + gy * gy)


def _edge_mask(value: np.ndarray, quantile: float) -> np.ndarray:
    magnitude = _gradient_magnitude(value)
    positive = magnitude[magnitude > 1e-6]
    if positive.size == 0:
        return np.zeros(value.shape, dtype=bool)
    threshold = max(float(np.quantile(positive, quantile)), 0.01)
    return magnitude >= threshold


def _boundary_mask(labels: np.ndarray) -> np.ndarray:
    boundary = np.zeros(labels.shape, dtype=bool)
    horizontal = labels[:, 1:] != labels[:, :-1]
    horizontal &= (labels[:, 1:] != 0) | (labels[:, :-1] != 0)
    vertical = labels[1:, :] != labels[:-1, :]
    vertical &= (labels[1:, :] != 0) | (labels[:-1, :] != 0)
    boundary[:, 1:] |= horizontal
    boundary[:, :-1] |= horizontal
    boundary[1:, :] |= vertical
    boundary[:-1, :] |= vertical
    return boundary


def _recall(reference: np.ndarray, observed: np.ndarray, radius: int) -> float:
    count = int(np.count_nonzero(reference))
    if count == 0:
        return 1.0
    return float(np.count_nonzero(reference & _dilate(observed, radius)) / count)


def _coarse_luminance_correlation(source: np.ndarray, candidate: np.ndarray) -> float:
    def resize(value: np.ndarray) -> np.ndarray:
        image = Image.fromarray(np.clip(np.rint(value * 255.0), 0, 255).astype(np.uint8))
        return np.asarray(image.resize((32, 18), Image.Resampling.BILINEAR), dtype=np.float32).ravel()

    left = resize(source)
    right = resize(candidate)
    left -= float(np.mean(left))
    right -= float(np.mean(right))
    denominator = float(np.linalg.norm(left) * np.linalg.norm(right))
    if denominator <= 1e-9:
        return 1.0 if np.allclose(left, right) else 0.0
    return float(np.dot(left, right) / denominator)


def evaluate_composition(
    capture_dir: Path,
    source_rgb: np.ndarray,
    admitted_rgb: np.ndarray,
    protected_core: np.ndarray,
    contract: Mapping[str, Any],
) -> dict[str, Any]:
    lock = contract["composition_lock"]
    radius = int(lock["edge_match_radius_px"])
    source_luma = _luminance(source_rgb)
    output_luma = _luminance(admitted_rgb)
    # Keep this witness focused on strong structural edges. Fine low-poly
    # facet edges are intentionally allowed to disappear during restyling;
    # semantic and depth boundaries are checked independently below.
    source_edges = _edge_mask(source_luma, 0.90)
    output_edges = _edge_mask(output_luma, 0.82)
    semantic = _load_npz_array(capture_dir / "semantic_ids.npz")
    instance = _load_npz_array(capture_dir / "instance_ids.npz")
    semantic_boundaries = _boundary_mask(semantic) | _boundary_mask(instance)
    depth = _load_npz_array(capture_dir / "depth_distance_to_camera_m.npz").astype(np.float32)
    finite_depth = np.isfinite(depth) & (depth > 0)
    finite_values = depth[finite_depth]
    if finite_values.size == 0:
        raise RestyleContractError("depth raster has no positive finite distance")
    depth_for_edges = depth.copy()
    depth_for_edges[~finite_depth] = float(np.max(finite_values))
    depth_edges = _edge_mask(np.log1p(depth_for_edges), 0.90)
    depth_edges |= _boundary_mask(finite_depth.astype(np.uint8))
    outside = ~protected_core
    if np.any(outside):
        delta = np.abs(source_rgb.astype(np.float32) - admitted_rgb.astype(np.float32)) / 255.0
        mean_delta = float(np.mean(delta[outside]))
    else:
        mean_delta = 0.0
    if np.any(protected_core):
        exact_fraction = float(
            np.mean(np.all(source_rgb[protected_core] == admitted_rgb[protected_core], axis=1))
        )
    else:
        exact_fraction = 1.0
    metrics = {
        "source_edge_recall": _recall(source_edges, output_edges, radius),
        # Recall alone detects removed structures but not a newly hallucinated
        # object.  This reciprocal witness measures how much of the candidate
        # structure is anchored to a source edge.  It is opt-in in v1 and
        # mandatory in the separate validated v2 contract.
        "output_edge_precision": _recall(output_edges, source_edges, radius),
        "semantic_boundary_recall": _recall(semantic_boundaries, output_edges, radius),
        "depth_boundary_recall": _recall(depth_edges, output_edges, radius),
        "coarse_luminance_correlation": _coarse_luminance_correlation(source_luma, output_luma),
        "mean_absolute_style_delta": mean_delta,
        "protected_core_exact_fraction": exact_fraction,
        "protected_core_pixel_count": int(np.count_nonzero(protected_core)),
    }
    gates = {
        "resolution_exact": source_rgb.shape == admitted_rgb.shape,
        "protected_core_exact": exact_fraction == 1.0,
        "source_edges_preserved": metrics["source_edge_recall"]
        >= float(lock["minimum_source_edge_recall"]),
        "output_edges_anchored": metrics["output_edge_precision"]
        >= float(lock.get("minimum_output_edge_precision", 0.0)),
        "semantic_boundaries_preserved": metrics["semantic_boundary_recall"]
        >= float(lock["minimum_semantic_boundary_recall"]),
        "depth_boundaries_preserved": metrics["depth_boundary_recall"]
        >= float(lock["minimum_depth_boundary_recall"]),
        "coarse_composition_preserved": metrics["coarse_luminance_correlation"]
        >= float(lock["minimum_coarse_luminance_correlation"]),
        "style_changed": metrics["mean_absolute_style_delta"]
        >= float(lock["minimum_mean_absolute_style_delta"]),
        "style_change_bounded": metrics["mean_absolute_style_delta"]
        <= float(lock["maximum_mean_absolute_style_delta"]),
    }
    return {
        "schema": "fireviewer.rgb-restyle.qa.v1",
        "metrics": metrics,
        "thresholds": {
            key: value
            for key, value in lock.items()
            if key.startswith("minimum_") or key.startswith("maximum_") or key.endswith("radius_px")
        },
        "gates": gates,
        "admission_status": "passed" if all(gates.values()) else "rejected",
    }


def _load_rgb(path: Path) -> np.ndarray:
    try:
        with Image.open(path) as image:
            return np.asarray(image.convert("RGB"), dtype=np.uint8)
    except OSError as exc:
        raise RestyleContractError(f"cannot decode RGB image {path}: {exc}") from exc


def _capture_key(capture_dir: Path) -> str:
    parts = list(capture_dir.parts)
    for index, part in enumerate(parts):
        if re.fullmatch(r"day\d+", part, re.IGNORECASE):
            return "/".join(parts[index:])
    return "/".join(parts[-4:])


def admit_candidate(
    capture_dir: Path,
    candidate_path: Path,
    *,
    contract_path: Path = DEFAULT_CONTRACT_PATH,
    output_dir: Path | None = None,
) -> dict[str, Any]:
    contract = load_contract(contract_path)
    inventory = inventory_capture(capture_dir, contract)
    source_path = inventory.capture_dir / "rgb.png"
    candidate = candidate_path.resolve()
    if candidate == source_path.resolve():
        raise RestyleContractError("source rgb.png cannot be used as the generated candidate")
    source_rgb = _load_rgb(source_path)
    generated_rgb = _load_rgb(candidate)
    if generated_rgb.shape != source_rgb.shape:
        report = {
            "schema": "fireviewer.rgb-restyle.qa.v1",
            "admission_status": "rejected",
            "gates": {"resolution_exact": False},
            "source_shape": list(source_rgb.shape),
            "candidate_shape": list(generated_rgb.shape),
        }
        raise AdmissionRejected(report)
    protected = build_protected_mask(
        inventory.capture_dir,
        contract,
        (inventory.height_px, inventory.width_px),
    )
    admitted_rgb = composite_protected_pixels(
        source_rgb,
        generated_rgb,
        protected,
        int(contract["composition_lock"]["protected_feather_radius_px"]),
    )
    report = evaluate_composition(
        inventory.capture_dir,
        source_rgb,
        admitted_rgb,
        protected,
        contract,
    )
    report["source_rgb_sha256"] = inventory.source_files["rgb.png"]["sha256"]
    report["candidate_rgb_sha256"] = sha256_file(candidate)
    report["source_binding_sha256"] = inventory.source_binding_sha256
    if report["admission_status"] != "passed":
        raise AdmissionRejected(report)

    current = inventory_capture(capture_dir, contract)
    if current.source_binding_sha256 != inventory.source_binding_sha256:
        raise RestyleContractError("source capture changed during candidate admission")
    destination = (
        output_dir.resolve()
        if output_dir is not None
        else inventory.capture_dir / contract["source_contract"]["derived_output_relative_dir"]
    )
    if destination.exists():
        raise RestyleContractError(f"immutable derived output already exists: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=".photoreal_v1-", dir=destination.parent))
    try:
        output_rgb = staging / "rgb.png"
        Image.fromarray(admitted_rgb, mode="RGB").save(output_rgb, format="PNG", optimize=False)
        report["admitted_rgb_sha256"] = sha256_file(output_rgb)
        report["capture_id"] = inventory.capture_id
        qa_path = staging / "qa.json"
        _write_json_atomic(qa_path, report)
        receipt = {
            "schema": "fireviewer.rgb-restyle.receipt.v1",
            "contract_id": contract["contract_id"],
            "contract_sha256": contract["_contract_sha256"],
            "workflow_sha256": contract["engine"]["api_workflow_sha256"],
            "capture_id": inventory.capture_id,
            "capture_key": _capture_key(inventory.capture_dir),
            "source_binding_sha256": inventory.source_binding_sha256,
            "source_files": inventory.source_files,
            "target_witness": inventory.target_witness,
            "candidate_rgb_sha256": sha256_file(candidate),
            "admitted_rgb_sha256": report["admitted_rgb_sha256"],
            "qa_sha256": sha256_file(qa_path),
            "protected_masks": contract["source_contract"]["protected_masks"],
            "metadata_policy": "source metadata retained by SHA-256 reference; no metadata file rewritten",
            "ai_provenance": {
                "ai_generated_or_modified": True,
                "model": contract["engine"]["models"][0]["source_repo"],
                "model_sha256": contract["engine"]["models"][0]["sha256"],
                "derived_rgb_only": True,
            },
            "release_gate": contract["release_gate"],
        }
        _write_json_atomic(staging / "restyle-receipt.json", receipt)
        os.replace(staging, destination)
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    return {
        "output_dir": str(destination),
        "rgb_path": str(destination / "rgb.png"),
        "qa_path": str(destination / "qa.json"),
        "receipt_path": str(destination / "restyle-receipt.json"),
        "admission_status": "passed",
    }


def _request_json(
    url: str,
    *,
    method: str = "GET",
    payload: Mapping[str, Any] | None = None,
    timeout: float = 30.0,
) -> dict[str, Any]:
    data = canonical_json_bytes(payload) if payload is not None else None
    headers = {"Content-Type": "application/json"} if data is not None else {}
    request = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            result = json.loads(response.read().decode("utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RestyleContractError(f"ComfyUI request failed for {url}: {exc}") from exc
    if not isinstance(result, dict):
        raise RestyleContractError(f"ComfyUI returned a non-object response for {url}")
    return result


def preflight_comfy(
    server: str,
    contract: Mapping[str, Any],
) -> dict[str, Any]:
    base = server.rstrip("/")
    stats = _request_json(f"{base}/system_stats")
    system = stats.get("system", {})
    version = str(system.get("comfyui_version", "0"))
    if _version_tuple(version) < _version_tuple(contract["engine"]["minimum_version"]):
        raise RestyleContractError(
            f"ComfyUI {version} is older than {contract['engine']['minimum_version']}"
        )
    missing_nodes: list[str] = []
    for class_type in contract["engine"]["required_node_classes"]:
        info = _request_json(f"{base}/object_info/{urllib.parse.quote(class_type)}")
        if class_type not in info:
            missing_nodes.append(class_type)
    if missing_nodes:
        raise RestyleContractError(f"ComfyUI is missing locked nodes: {missing_nodes}")
    return {
        "comfyui_version": version,
        "required_nodes_present": True,
        "device": stats.get("devices", [{}])[0].get("name") if stats.get("devices") else None,
    }


def _upload_image(
    server: str,
    path: Path,
    *,
    filename: str,
    subfolder: str,
) -> dict[str, Any]:
    boundary = "----FireViewer" + uuid.uuid4().hex
    chunks: list[bytes] = []

    def field(name: str, value: str) -> None:
        chunks.extend(
            [
                f"--{boundary}\r\n".encode(),
                f'Content-Disposition: form-data; name="{name}"\r\n\r\n'.encode(),
                value.encode(),
                b"\r\n",
            ]
        )

    field("type", "input")
    field("overwrite", "true")
    field("subfolder", subfolder)
    chunks.extend(
        [
            f"--{boundary}\r\n".encode(),
            f'Content-Disposition: form-data; name="image"; filename="{filename}"\r\n'.encode(),
            b"Content-Type: image/png\r\n\r\n",
            path.read_bytes(),
            b"\r\n",
            f"--{boundary}--\r\n".encode(),
        ]
    )
    request = urllib.request.Request(
        server.rstrip("/") + "/upload/image",
        data=b"".join(chunks),
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=120.0) as response:
            result = json.loads(response.read().decode("utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RestyleContractError(f"ComfyUI image upload failed: {exc}") from exc
    if not isinstance(result, dict):
        raise RestyleContractError("ComfyUI upload returned an invalid response")
    return result


def execute_single_job(
    manifest_path: Path,
    *,
    server: str = DEFAULT_COMFY_SERVER,
    confirm_gpu_workload: bool = False,
    timeout_seconds: float = 900.0,
    attempt: int = 0,
    seed_override: int | None = None,
) -> dict[str, Any]:
    if not confirm_gpu_workload:
        raise RestyleContractError("GPU execution requires --confirm-gpu-workload")
    manifest = _load_json(manifest_path.resolve())
    if manifest.get("schema") != "fireviewer.rgb-restyle.job.v1":
        raise RestyleContractError("unsupported RGB restyle job manifest")
    contract = load_contract(Path(manifest["contract_path"]))
    if manifest.get("contract_sha256") != contract["_contract_sha256"]:
        raise RestyleContractError("job contract changed after preparation")
    prompt_path = Path(manifest["prompt_path"])
    if sha256_file(prompt_path) != manifest.get("prompt_sha256"):
        raise RestyleContractError("prepared ComfyUI prompt changed")
    source_path = Path(manifest["source_rgb_path"])
    expected_source_sha = manifest["capture"]["source_files"]["rgb.png"]["sha256"]
    if sha256_file(source_path) != expected_source_sha:
        raise RestyleContractError("source RGB changed after job preparation")
    runtime = preflight_comfy(server, contract)
    upload = manifest["comfy_upload"]
    uploaded = _upload_image(
        server,
        source_path,
        filename=upload["filename"],
        subfolder=upload["subfolder"],
    )
    prompt = _load_json(prompt_path)
    base_seed = int(manifest["seed"]) if seed_override is None else int(seed_override)
    attempt_seed = derive_attempt_seed(base_seed, attempt)
    # Always override the persisted workflow stem.  Older prepared manifests
    # used ``candidate_00001``; the actual ComfyUI filename now includes both
    # the immutable job id and the retry number.
    prompt["11"]["inputs"]["noise_seed"] = attempt_seed
    prompt["17"]["inputs"]["filename_prefix"] = candidate_output_prefix(
        str(manifest["job_id"]), attempt
    )
    uploaded_name = uploaded.get("name", upload["filename"])
    uploaded_subfolder = uploaded.get("subfolder", upload["subfolder"])
    prompt["4"]["inputs"]["image"] = f"{uploaded_subfolder}/{uploaded_name}"
    client_id = "fireviewer-rgb-restyle-" + manifest["job_id"]
    queued = _request_json(
        server.rstrip("/") + "/prompt",
        method="POST",
        payload={"prompt": prompt, "client_id": client_id},
        timeout=30.0,
    )
    prompt_id = queued.get("prompt_id")
    if not isinstance(prompt_id, str):
        raise RestyleContractError(f"ComfyUI did not return a prompt_id: {queued}")
    deadline = time.monotonic() + timeout_seconds
    history: dict[str, Any] | None = None
    while time.monotonic() < deadline:
        response = _request_json(
            server.rstrip("/") + f"/history/{urllib.parse.quote(prompt_id)}",
            timeout=30.0,
        )
        if prompt_id in response:
            history = response[prompt_id]
            break
        time.sleep(1.0)
    if history is None:
        raise RestyleContractError(f"ComfyUI prompt timed out: {prompt_id}")
    outputs = history.get("outputs", {}).get("17", {}).get("images", [])
    if len(outputs) != 1:
        raise RestyleContractError(f"expected one ComfyUI output image, got {len(outputs)}")
    output = outputs[0]
    query = urllib.parse.urlencode(
        {
            "filename": output["filename"],
            "subfolder": output.get("subfolder", ""),
            "type": output.get("type", "output"),
        }
    )
    candidate_path = manifest_path.resolve().parent / (
        f"candidate-{manifest['job_id']}-attempt-{attempt:02d}.png"
    )
    try:
        with urllib.request.urlopen(server.rstrip("/") + "/view?" + query, timeout=120.0) as response:
            candidate_path.write_bytes(response.read())
    except OSError as exc:
        raise RestyleContractError(f"cannot download ComfyUI candidate: {exc}") from exc
    receipt = {
        "schema": "fireviewer.rgb-restyle.runtime-receipt.v1",
        "job_id": manifest["job_id"],
        "prompt_id": prompt_id,
        "runtime": runtime,
        "candidate_path": str(candidate_path),
        "candidate_sha256": sha256_file(candidate_path),
        "source_rgb_sha256": expected_source_sha,
        "contract_sha256": contract["_contract_sha256"],
        "workflow_sha256": contract["engine"]["api_workflow_sha256"],
        "attempt": attempt,
        "seed": attempt_seed,
    }
    _write_json_atomic(manifest_path.resolve().parent / "runtime-receipt.json", receipt)
    return receipt


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    inspect_parser = subparsers.add_parser("inspect", help="validate one source capture")
    inspect_parser.add_argument("--capture-dir", type=Path, required=True)
    inspect_parser.add_argument("--contract", type=Path, default=DEFAULT_CONTRACT_PATH)

    prepare_parser = subparsers.add_parser("prepare", help="prepare one immutable dry-run job")
    prepare_parser.add_argument("--capture-dir", type=Path, required=True)
    prepare_parser.add_argument("--job-root", type=Path, required=True)
    prepare_parser.add_argument("--contract", type=Path, default=DEFAULT_CONTRACT_PATH)
    prepare_parser.add_argument("--model-root", type=Path, default=DEFAULT_MODEL_ROOT)
    prepare_parser.add_argument(
        "--skip-model-hash",
        action="store_true",
        help="verify model presence and size only; production preparation should not use this",
    )

    run_parser = subparsers.add_parser("run", help="submit one prepared pilot to ComfyUI")
    run_parser.add_argument("--job-manifest", type=Path, required=True)
    run_parser.add_argument("--server", default=DEFAULT_COMFY_SERVER)
    run_parser.add_argument("--timeout-seconds", type=float, default=900.0)
    run_parser.add_argument("--confirm-gpu-workload", action="store_true")

    admit_parser = subparsers.add_parser("admit", help="QA and admit one derived RGB")
    admit_parser.add_argument("--capture-dir", type=Path, required=True)
    admit_parser.add_argument("--candidate-rgb", type=Path, required=True)
    admit_parser.add_argument("--contract", type=Path, default=DEFAULT_CONTRACT_PATH)
    admit_parser.add_argument("--output-dir", type=Path)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.command == "inspect":
            contract = load_contract(args.contract)
            result = inventory_capture(args.capture_dir, contract).as_dict(include_local_path=True)
        elif args.command == "prepare":
            manifest_path, manifest = prepare_job(
                args.capture_dir,
                args.job_root,
                contract_path=args.contract,
                model_root=args.model_root,
                hash_models=not args.skip_model_hash,
            )
            result = {"manifest_path": str(manifest_path), "job": manifest}
        elif args.command == "run":
            result = execute_single_job(
                args.job_manifest,
                server=args.server,
                confirm_gpu_workload=args.confirm_gpu_workload,
                timeout_seconds=args.timeout_seconds,
            )
        elif args.command == "admit":
            result = admit_candidate(
                args.capture_dir,
                args.candidate_rgb,
                contract_path=args.contract,
                output_dir=args.output_dir,
            )
        else:  # pragma: no cover - argparse prevents this branch
            raise RestyleContractError(f"unsupported command: {args.command}")
    except AdmissionRejected as exc:
        print(json.dumps(exc.report, ensure_ascii=False, indent=2, sort_keys=True))
        return 3
    except RestyleContractError as exc:
        print(json.dumps({"status": "error", "error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 2
    print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
